const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('docs/design/plato_unseen_exchange.html','utf8');
const a=html.indexOf('// BEGIN PLATO UNSEEN EXCHANGE PAPER MODEL'),b=html.indexOf('// END PLATO UNSEEN EXCHANGE PAPER MODEL');assert.ok(a>=0&&b>a);
const M=vm.runInNewContext(html.slice(a,b)+'\nPlatoUnseenExchangePaper');
const snap=s=>JSON.stringify(s),unchanged=(s,fn)=>{const before=snap(s);assert.equal(fn(),false);assert.equal(snap(s),before);};
const buy=M.create();assert.equal(M.transact(buy,'buy'),true);assert.equal(buy.gold,20);assert.equal(buy.inventory.length,1);assert.equal(buy.shops[2].quantity,0);assert.equal(buy.shops[2].paid,100);assert.equal(buy.used[2],true);unchanged(buy,()=>M.transact(buy,'take'));M.advance(buy);assert.equal(buy.gold,20);unchanged(buy,()=>M.transact(buy,'buy'));assert.equal(M.transact(buy,'take'),true);assert.equal(buy.inventory.length,2);assert.equal(buy.gold,20);
const take=M.create();M.transact(take,'take');assert.equal(take.gold,120);assert.equal(take.shops[2].paid,0);assert.equal(take.inventory.length,1);unchanged(take,()=>M.advance(take));unchanged(take,()=>M.ordinary(take));unchanged(take,()=>M.discard(take));unchanged(take,()=>M.setActive(take,false));const restored=M.copy(take);assert.equal(M.pay(restored),true);assert.equal(restored.gold,20);assert.equal(restored.inventory.length,1);assert.equal(restored.receipts[0].paid,100);assert.equal(restored.records[0].paid,0);assert.equal(restored.shops[2].paid,100);unchanged(restored,()=>M.pay(restored));M.close(restored);unchanged(restored,()=>M.pay(restored));unchanged(restored,()=>M.close(restored));
const quote=M.create();M.transact(quote,'take');quote.shops[2].price=300;M.pay(quote);assert.equal(quote.gold,20);assert.equal(quote.records.at(-1).price,100);
const leave=M.create();M.transact(leave,'leave');assert.equal(leave.gold,120);assert.equal(leave.inventory.length,0);assert.equal(leave.shops[2].quantity,1);assert.equal(leave.used[2],true);assert.equal(M.ordinary(leave),true);assert.equal(leave.gold,20);assert.equal(leave.inventory.length,1);assert.equal(leave.used[2],true);unchanged(leave,()=>M.ordinary(leave));
const poor=M.create('poor');unchanged(poor,()=>M.transact(poor,'buy'));M.transact(poor,'take');unchanged(poor,()=>M.pay(poor));assert.equal(poor.gold,80);M.close(poor);M.advance(poor);M.transact(poor,'buy');assert.equal(poor.gold,0);assert.equal(poor.inventory.length,2);
const gift=M.create('gift');assert.equal(M.eligible(gift),false);unchanged(gift,()=>M.transact(gift,'take'));assert.equal(M.ordinary(gift),true);assert.equal(gift.gold,120);assert.equal(gift.receipts.length,0);assert.equal(gift.used[2],false);
const full=M.create('full');assert.equal(M.eligible(full),false);unchanged(full,()=>M.transact(full,'take'));unchanged(full,()=>M.ordinary(full));assert.equal(M.discard(full),true);assert.equal(M.eligible(full),true);M.transact(full,'take');assert.equal(full.inventory.length,2);
const owner=M.create();M.transact(owner,'take');M.close(owner);M.advance(owner);unchanged(owner,()=>M.pay(owner));M.transact(owner,'take');M.pay(owner);assert.equal(owner.gold,40);assert.equal(owner.receipts[0].paid,0);assert.equal(owner.receipts[1].paid,80);assert.equal(owner.shops[2].paid,0);assert.equal(owner.shops[3].paid,80);
const active=M.create();M.transact(active,'leave');M.setActive(active,false);M.setActive(active,true);active.phase='shop';assert.equal(M.eligible(active),false);unchanged(active,()=>M.transact(active,'take'));assert.equal(active.used[2],true);
const base=M.create('ready',true);assert.equal(M.eligible(base),false);unchanged(base,()=>M.transact(base,'take'));unchanged(base,()=>M.setActive(base,true));M.ordinary(base);assert.equal(base.gold,20);assert.equal(base.inventory.length,1);
const n=M.create();unchanged(n,()=>M.respond(n,'text'));unchanged(n,()=>M.transact(n,'virtue'));M.transact(n,'leave');const before=snap(n);M.respond(n,' '.repeat(20));assert.equal(n.notes[2],null);M.respond(n,'x'.repeat(450));assert.equal(n.notes[2].length,400);n.notes={};assert.equal(snap(n),before);unchanged(n,()=>M.respond(n,42));M.respond(n,'旧理由');M.advance(n);assert.equal(n.notes[2],'旧理由');
let endings=0;
function invariants(s){assert.ok(s.gold>=0);assert.ok(s.inventory.length<=s.capacity);assert.equal(new Set(s.inventory.map(x=>x.id)).size,s.inventory.length);for(const act of[2,3]){const p=s.shops[act];assert.ok([0,1].includes(p.quantity));assert.equal(s.records.filter(r=>r.act===act&&['buy','ordinary','pay'].includes(r.kind)).reduce((v,r)=>v+r.paid,0),p.paid);assert.ok(s.records.filter(r=>r.act===act&&['buy','take','leave'].includes(r.kind)).length<=1);}assert.equal(s.records.filter(r=>r.paid!==undefined).reduce((v,r)=>v+r.paid,0)+s.gold,s.fixture==='poor'?80:120);}
function explore(s){invariants(s);if(s.phase==='complete'){endings++;return;}const moves=[];if(M.eligible(s))for(const choice of['buy','take','leave'])moves.push(n=>M.transact(n,choice));else if(s.phase==='shop')moves.push(n=>M.leaveOrdinary(n));moves.push(M.ordinary,M.pay,M.close,M.discard,M.advance);for(const fn of moves){const next=M.copy(s);if(fn(next))explore(next);}}
for(const fixture of['ready','poor','full','gift'])for(const baseline of[false,true])explore(M.create(fixture,baseline));assert.ok(endings>50);console.log('无名交易纸面检查通过：实际付款/单件取得/引用无关重建/原价快照/卖方归属/资格不刷新/跨幕保留/非法操作原子拒绝；'+endings+'条完整有限路径。不是原生存档或正义认证。');
