// Limited fictional loop; no native combat, exit hooks, save or philosophical truth claims.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../docs/design/socrates_retreat.html'),'utf8');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
const code=html.match(/\/\/ BEGIN SOCRATES RETREAT PAPER MODEL([\s\S]*?)\/\/ END SOCRATES RETREAT PAPER MODEL/)[1],context={};vm.runInNewContext(code+'\nglobalThis.paper=SocratesRetreatPaper;',context);const p=context.paper;
let total=0;const check=(name,run)=>{run();total++;console.log('PASS '+name);};const snapshot=s=>JSON.stringify(s);
function unchanged(s,fn){const before=snapshot(s);assert.equal(fn(),false);assert.equal(snapshot(s),before);}
function begun(fixture='winnable',definition='necessary'){const s=p.create(fixture);assert.equal(p.begin(s,definition),true);return s;}
function retreat(s,purpose=null){assert.equal(p.request(s),true);const id=s.request.id;assert.equal(p.confirm(s,id,purpose),true);return id;}
function win(s){let n=0;while(s.phase==='combat'){p.play(s,'attack');if(s.phase==='combat'){p.play(s,'defend');p.endTurn(s);}assert.ok(++n<10);}assert.equal(s.phase,'review');}
check('Explicit or unstated definitions precede action without inventing a belief',()=>{for(const d of ['necessary','purpose','unstated']){const s=begun('winnable',d);assert.equal(s.definition,d);assert.equal(s.judgment,null);assert.equal(s.actionPurpose,null);assert.equal(s.spent.length,0);}const s=p.create();unchanged(s,()=>p.begin(s,'bad'));unchanged(s,()=>p.request(s));});
check('Cancel preserves battle and resource state; a later request has a new token',()=>{const s=begun();p.request(s);const old=s.request.id;const resources=[s.hp,s.gold,s.energy,s.enemyHp,s.block].join(',');assert.equal(p.cancel(s,old),true);assert.equal([s.hp,s.gold,s.energy,s.enemyHp,s.block].join(','),resources);assert.equal(s.spent.length,0);assert.equal(s.actionPurpose,null);p.request(s);assert.notEqual(s.request.id,old);unchanged(s,()=>p.confirm(s,old));});
check('Confirm loses all victory reward, preserves paid losses and prior persistent gold',()=>{const s=begun('persistent');p.play(s,'attack');p.play(s,'defend');p.endTurn(s);assert.equal(s.hp,12);const id=retreat(s,'先保旅程');assert.equal(s.hp,12);assert.equal(s.gold,7);assert.equal(s.rewardStatus,'lost');assert.equal(s.victories,0);assert.equal(s.spent.join(','),'1');assert.equal(s.processed.join(','),'n1');assert.equal(s.actionPurpose,'先保旅程');unchanged(s,()=>p.confirm(s,id));unchanged(s,()=>p.cancel(s,id));});
check('Invalid, dead and stale confirmations leave resources and claims unchanged',()=>{for(const mutate of [s=>s.hp=0,s=>s.epoch++,s=>s.node='n2',s=>s.kind='boss',s=>s.spent.push(1)]){const s=begun();p.request(s);const id=s.request.id;mutate(s);unchanged(s,()=>p.confirm(s,id));}const s=begun();p.request(s);unchanged(s,()=>p.confirm(s,s.request.id,''));unchanged(s,()=>p.confirm(s,s.request.id,'x'.repeat(301)));});
check('Boss never retreats; explicit ordinary request blocks further player actions until resolved',()=>{const b=begun('boss');assert.equal(p.available(b),false);unchanged(b,()=>p.request(b));const s=begun();p.request(s);unchanged(s,()=>p.play(s,'attack'));unchanged(s,()=>p.endTurn(s));unchanged(s,()=>p.request(s));});
check('Normal victory earns reward, retains retreat opportunity and does not certify courage',()=>{const s=begun();win(s);assert.equal(s.hp,19);assert.equal(s.gold,10);assert.equal(s.victories,1);assert.equal(s.spent.length,0);assert.equal(s.judgment,null);assert.equal(s.definition,'necessary');assert.equal(p.tension(s),false);p.judge(s,'courageous');p.setScope(s,true);assert.equal(p.tension(s),false);});
check('Unknown intent stays unknown before action; retreat does not create a risk prediction',()=>{const s=begun('hidden');retreat(s);assert.equal(s.hp,16);assert.equal(s.judgment,null);assert.equal('predictedDamage' in s,false);assert.equal(s.history.some(x=>x.includes('必死')),false);});
check('Keeping standard but prioritising another purpose is not an automatic contradiction',()=>{const s=begun('danger');retreat(s,'这次保旅程');p.judge(s,'standardElse');p.setScope(s,true);assert.equal(p.tension(s),false);assert.equal(s.definition,'necessary');assert.equal(s.judgment,'standardElse');});
check('Only explicit local courage plus explicit scope raises a same-range question',()=>{for(const definition of ['necessary','purpose','unstated']){const s=begun('danger',definition);retreat(s);assert.equal(p.tension(s),false);p.judge(s,'courageous');assert.equal(p.tension(s),false);p.setScope(s,true);assert.equal(p.tension(s),definition==='necessary');assert.equal('virtueScore' in s,false);assert.equal('isCourageous' in s,false);}});
check('Revision targets either statement or leaves question open without changing resources',()=>{for(const a of ['dropNecessary','withdrawJudgment','leaveOpen']){const s=begun('danger');retreat(s);p.judge(s,'courageous');p.setScope(s,true);const r=[s.hp,s.gold,s.spent.join(','),s.victories].join(';');assert.equal(p.adjust(s,a),true);assert.equal([s.hp,s.gold,s.spent.join(','),s.victories].join(';'),r);assert.equal(s.originalDefinition,'necessary');assert.equal(p.tension(s),a==='leaveOpen');unchanged(s,()=>p.adjust(s,a));}});
check('Every response or no response can proceed along the same legal edge with equal resources',()=>{for(const definition of ['necessary','purpose','unstated'])for(const judgment of [null,'standardElse','courageous','notJudged','unanswered']){const s=begun('danger',definition);retreat(s);if(judgment!==null)p.judge(s,judgment);assert.equal(p.proceed(s,'n2'),true);assert.equal(s.hp,12);assert.equal(s.gold,0);assert.equal(s.spent.join(','),'1');assert.equal(s.judgment,judgment);}});
check('Processed node cannot repeat; spent opportunity follows next ordinary combat',()=>{const s=begun();const token=retreat(s);unchanged(s,()=>p.proceed(s,'n1'));unchanged(s,()=>p.proceed(s,'unknown'));p.proceed(s,'n2');p.enter(s);assert.equal(p.available(s),false);assert.equal(s.hp,20);assert.equal(s.gold,0);unchanged(s,()=>p.request(s));unchanged(s,()=>p.confirm(s,token));});
check('Last ordinary combat legally leads to Boss without a refreshed escape',()=>{const s=begun('last');retreat(s);assert.equal(p.destinations(s).join(','),'n4');p.proceed(s,'n4');p.enter(s);assert.equal(s.kind,'boss');assert.equal(p.available(s),false);unchanged(s,()=>p.request(s));});
check('Death does not give victory, retroactive review, escape, reward or resurrection',()=>{const s=begun('danger');p.play(s,'defend');p.endTurn(s);assert.equal(s.phase,'dead');assert.equal(s.hp,0);assert.equal(s.gold,0);assert.equal(s.victories,0);assert.equal(s.spent.length,0);for(const fn of [()=>p.request(s),()=>p.judge(s,'courageous'),()=>p.proceed(s,'n2'),()=>p.enter(s)])unchanged(s,fn);});
check('Continued action purpose is explicit and survives victory; no retroactive death or confirm edits',()=>{const s=begun();unchanged(s,()=>p.recordPurpose(s,''));assert.equal(p.recordPurpose(s,'从现在起争取奖励'),true);win(s);assert.equal(s.actionPurpose,'从现在起争取奖励');unchanged(s,()=>p.recordPurpose(s,'改旧理由'));const r=begun();p.recordPurpose(r,'争取奖励');p.request(r);unchanged(r,()=>p.recordPurpose(r,'请求中改'));p.confirm(r,r.request.id,null);assert.equal(r.actionPurpose,null);assert.ok(r.history.some(x=>x.includes('争取奖励')));});
check('Rest path can continue legally without recovery or reentering old nodes',()=>{const s=begun();retreat(s);p.proceed(s,'n3');assert.equal(s.hp,20);assert.equal(s.gold,0);assert.equal(p.destinations(s).join(','),'n4');unchanged(s,()=>p.enter(s));unchanged(s,()=>p.proceed(s,'n2'));assert.equal(p.proceed(s,'n4'),true);assert.ok(s.processed.includes('n3'));assert.equal(p.enter(s),true);assert.equal(s.kind,'boss');});
check('Next encounter snapshots the revised standard without rewriting the previous testimony',()=>{const s=begun();retreat(s);p.judge(s,'courageous');p.setScope(s,true);p.adjust(s,'dropNecessary');p.proceed(s,'n2');assert.equal(s.encounters[0].originalDefinition,'necessary');assert.equal(s.encounters[0].definition,'actionNotRequired');assert.equal(s.encounters[0].judgment,'courageous');p.enter(s);assert.equal(s.originalDefinition,'actionNotRequired');assert.equal(s.judgment,null);assert.equal(s.encounters[0].originalDefinition,'necessary');});
check('Player actions close the current retreat point; expression and cancelled requests do not',()=>{for(const card of ['attack','defend']){const s=begun();assert.equal(p.available(s),true);p.recordPurpose(s,'从现在起');p.request(s);p.cancel(s,s.request.id);assert.equal(p.available(s),true);p.play(s,card);assert.equal(p.available(s),false);unchanged(s,()=>p.request(s));p.endTurn(s);assert.equal(s.phase,'combat');assert.equal(p.available(s),true);}const s=begun();p.request(s);const id=s.request.id;s.played.push('attack');unchanged(s,()=>p.confirm(s,id));});
check('Legacy action-afterwards rule has a free persistent-gain prefix under the same fixture',()=>{const immediate=p.create('harvest','afterAction'),harvest=p.create('harvest','afterAction');for(const s of [immediate,harvest])p.begin(s,'unstated');retreat(immediate);p.play(harvest,'harvest');assert.equal(harvest.enemyHp,15);assert.equal(harvest.victories,0);assert.equal(harvest.rewardStatus,null);retreat(harvest);assert.equal(harvest.hp,immediate.hp);assert.equal(harvest.gold,3);assert.equal(immediate.gold,0);assert.equal(harvest.rewardStatus,'lost');assert.equal(harvest.spent.join(','),'1');});
check('New timing gives three concrete outcomes without rolling back persistent rewards',()=>{const immediate=begun('harvest'),retreated=begun('harvest'),continued=begun('harvest');retreat(immediate);for(const s of [retreated,continued]){p.play(s,'harvest');assert.equal(s.gold,3);assert.equal(s.victories,0);unchanged(s,()=>p.request(s));p.play(s,'defend');p.endTurn(s);assert.equal(s.hp,12);assert.equal(p.available(s),true);}retreat(retreated);win(continued);assert.equal([immediate.hp,immediate.gold].join(','),'16,0');assert.equal([retreated.hp,retreated.gold].join(','),'12,3');assert.equal([continued.hp,continued.gold].join(','),'4,13');assert.equal(continued.spent.length,0);assert.equal(retreated.victories,0);assert.equal(retreated.gainHistory.length,1);});
check('A lethal gain prefix cannot restore retreat after the enemy consequence',()=>{const s=begun('harvestDanger');p.play(s,'harvest');p.play(s,'defend');unchanged(s,()=>p.request(s));p.endTurn(s);assert.equal(s.phase,'dead');assert.equal(s.hp,0);assert.equal(s.gold,3);assert.equal(s.victories,0);assert.equal(s.spent.length,0);unchanged(s,()=>p.request(s));unchanged(s,()=>p.proceed(s,'n2'));});
check('Persistent gain requires an actual kill and never repeats on an empty target',()=>{const s=begun('harvest');s.sideHp=10;p.play(s,'harvest');assert.equal(s.sideHp,5);assert.equal(s.gold,0);assert.equal(s.gainHistory.length,0);unchanged(s,()=>p.play(s,'harvest'));p.play(s,'defend');p.endTurn(s);p.play(s,'harvest');assert.equal(s.gold,3);assert.equal(s.gainHistory.length,1);p.play(s,'defend');p.endTurn(s);unchanged(s,()=>p.play(s,'harvest'));assert.equal(s.gold,3);});
check('Taking one retreat does not allow node repetition or a second escape after a new gain',()=>{const s=begun('harvest');p.play(s,'harvest');p.play(s,'defend');p.endTurn(s);retreat(s);unchanged(s,()=>p.proceed(s,'n1'));p.proceed(s,'n2');p.enter(s);assert.equal(s.encounters[0].persistentGained,3);assert.equal(s.persistentGained,0);p.play(s,'harvest');assert.equal(s.gold,6);assert.equal(s.gainHistory.length,2);assert.equal(s.victories,0);assert.equal(p.available(s),false);unchanged(s,()=>p.request(s));assert.equal(s.processed.join(','),'n1');});
check('Rule windows are recorded once per stable round; queries and cancelled requests do not mint them',()=>{const s=begun();assert.equal(s.retreatWindows.length,1);assert.equal(s.retreatWindows[0].allowed,true);const before=snapshot(s);for(let i=0;i<100;i++){p.available(s);p.inquiry(s);p.opportunity(s);}assert.equal(snapshot(s),before);p.request(s);p.cancel(s,s.request.id);assert.equal(s.retreatWindows.length,1);p.play(s,'defend');assert.equal(p.available(s),false);p.endTurn(s);assert.equal(s.retreatWindows.map(w=>w.turn).join(','),'1,2');assert.equal(s.retreatWindows.every(w=>w.allowed),true);});
check('Boss victory preserves explicit judgments without inventing a voluntary refusal of retreat',()=>{for(const judgment of [null,'courageous','notJudged','unanswered']){const s=begun('boss');win(s);assert.equal(s.retreatWindows.every(w=>!w.allowed&&w.reason==='boss'),true);if(judgment!==null)p.judge(s,judgment);p.proceed(s,'n5');const q=p.inquiry(s);assert.equal(q.key,'noRetreatOption');assert.equal(q.judgment,judgment);assert.equal(q.purpose,null);assert.match(q.opportunity,/不等于完全没有行动选择/);if(judgment===null)assert.match(q.question,/没有留下自评/);if(judgment==='unanswered')assert.match(q.question,/明确暂不回应/);}});
check('Spent opportunity in the next combat cannot borrow an earlier legal window',()=>{const s=begun();retreat(s);p.proceed(s,'n2');const old=snapshot(s.encounters[0]);assert.equal(s.encounters[0].retreatWindows[0].allowed,true);p.enter(s);assert.equal(s.retreatWindows[0].allowed,false);assert.equal(s.retreatWindows[0].reason,'spent');win(s);p.proceed(s,'n4');assert.equal(snapshot(s.encounters[0]),old);const q=p.inquiry(s);assert.equal(q.key,'noRetreatOption');assert.match(q.opportunity,/本幕机会已用尽/);assert.equal(s.encounters[1].retreatWindows.every(w=>!w.allowed),true);});
check('Explicit standard revision, local withdrawal and open question lead to different later inquiries',()=>{const keys=[];for(const adjustment of ['dropNecessary','withdrawJudgment','leaveOpen']){const s=begun();retreat(s);p.judge(s,'courageous');p.setScope(s,true);p.adjust(s,adjustment);p.proceed(s,'n2');const q=p.inquiry(s);keys.push(q.key);assert.equal(q.originalDefinition,'necessary');assert.equal(q.definition,adjustment==='dropNecessary'?'actionNotRequired':'necessary');assert.equal(q.judgment,adjustment==='withdrawJudgment'?'withdrawn':'courageous');assert.equal(s.hp,20);assert.equal(s.gold,0);}assert.equal(keys.join(','),'revisedStandard,withdrawnJudgment,openTension');});
check('Other purpose, pending scope, no judgment and silence stay distinct; new reasons do not rewrite old facts',()=>{const expected={standardElse:'otherPurpose',courageous:'scopePending',notJudged:'notJudged',unanswered:'deferred',none:'unanswered'};for(const judgment of ['standardElse','courageous','notJudged','unanswered',null]){const s=begun();retreat(s,'<b>旧目的</b>');if(judgment!==null)p.judge(s,judgment);p.proceed(s,'n2');const q=p.inquiry(s),old=snapshot(s.encounters[0]);assert.equal(q.key,expected[judgment??'none']);assert.equal(q.purpose,'<b>旧目的</b>');p.enter(s);assert.equal(s.actionPurpose,null);p.recordPurpose(s,'从此刻的新目的');s.retreatWindows[0].reason='other';assert.equal(snapshot(s.encounters[0]),old);assert.equal(p.inquiry(s).purpose,'<b>旧目的</b>');assert.equal(Object.isFrozen(q),true);}});
console.log(`PASS ${total} authored retreat checks; native exit/save and philosophical experience not exercised.`);
