const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {pathToFileURL}=require('node:url'),{chromium}=require(process.argv[2]||'playwright');
const output=path.resolve('bin/design');fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,channel:process.argv[3]||'msedge'});try{
  const page=await browser.newPage({viewport:{width:860,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve('docs/design/socrates_retreat.html')).href);const b=name=>page.getByRole('button',{name,exact:true});
  await page.getByLabel('纸面处境').selectOption('persistent');await b('不后退是勇敢的必要条件').click();await b('基础攻击：1费，5伤害').click();await b('基础防御：1费，5格挡').click();await b('结束回合').click();assert.match(await page.locator('#state').innerText(),/生命12.*金币7/);
  await b('请求撤离').click();await page.getByLabel('这一次为了什么撤离？可留空').fill('取消不会提交的理由');await b('取消，回到战斗').click();assert.match(await page.locator('#state').innerText(),/尚未使用/);await b('请求撤离').click();assert.equal(await page.locator('#purpose').inputValue(),'');await page.getByLabel('这一次为了什么撤离？可留空').fill('<b>这次先保旅程</b>');await b('确认撤离').click();assert.match(await page.locator('#state').innerText(),/生命12.*金币7.*已用尽/);assert.match(await page.locator('#resourceResult').innerText(),/整场胜利奖励放弃/);assert.equal(await page.locator('#actionPurpose b').count(),0);
  assert.equal(await page.locator('#destinations button').count(),2);await b('我认为这次行动也可以勇敢').click();assert.match(await page.locator('#question').innerText(),/先检查旧句/);await page.getByLabel('我确认原“不退”必要条件也覆盖本次处境').check();assert.match(await page.locator('#question').innerText(),/两句在同一范围如何相容/);
  for(const[width,theme]of[[860,'light'],[360,'dark'],[320,'light']]){await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});const size=await page.locator('body').evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth}));assert.ok(size.scroll<=size.client+1,JSON.stringify({width,...size}));await page.screenshot({path:path.join(output,`socrates_retreat_${width}_${theme}.png`),fullPage:true});}
  await b('撤回本次勇敢判断').click();assert.match(await page.locator('#judgment').innerText(),/明确撤回/);await b('前往下一普通战斗').click();await b('进入此处固定战斗').click();assert.equal(await b('请求撤离').isDisabled(),true);assert.match(await page.locator('#state').innerText(),/生命12.*金币7/);
  await page.getByLabel('纸面处境').selectOption('danger');await b('不后退是勇敢的必要条件').click();await b('请求撤离').click();await b('确认撤离').click();await b('保留标准，这次优先别的目的').click();assert.match(await page.locator('#judgment').innerText(),/不自动矛盾/);assert.equal(await page.locator('#adjustments').isVisible(),false);
  await page.getByLabel('纸面处境').selectOption('hidden');await b('不提出通用说法').click();assert.match(await page.locator('#battle').innerText(),/意图未知/);assert.doesNotMatch(await page.locator('#battle').innerText(),/攻击9/);await b('请求撤离').click();await b('确认撤离').click();assert.match(await page.locator('#definition').innerText(),/没有提出通用说法/);await b('前往下一普通战斗').click();
  await page.getByLabel('纸面处境').selectOption('boss');await b('行动形式要结合目的说明').click();assert.equal(await b('请求撤离').isDisabled(),true);await page.getByLabel('从现在起，继续为了什么？可不填写').fill('争取本场奖励');await b('记录继续的理由').click();await b('基础攻击：1费，5伤害').click();await b('基础防御：1费，5格挡').click();await b('结束回合').click();await b('基础攻击：1费，5伤害').click();assert.match(await page.locator('#resourceResult').innerText(),/正常10金币/);assert.match(await page.locator('#state').innerText(),/尚未使用/);assert.equal(await page.locator('#actionPurpose').innerText(),'争取本场奖励');
  await page.getByLabel('纸面处境').selectOption('winnable');await b('不提出通用说法').click();await b('请求撤离').click();await b('确认撤离').click();await b('前往休息处（仅位置，不模拟恢复）').click();await b('前往Boss').click();await b('进入此处固定战斗').click();assert.equal(await b('请求撤离').isDisabled(),true);
  await page.getByLabel('纸面处境').selectOption('last');await b('不提出通用说法').click();await b('请求撤离').click();await b('确认撤离').click();assert.equal(await page.locator('#destinations button').count(),1);await b('前往Boss').click();await b('进入此处固定战斗').click();assert.equal(await b('请求撤离').isDisabled(),true);
  await page.getByLabel('纸面处境').selectOption('danger');await b('不提出通用说法').click();await b('基础防御：1费，5格挡').click();await b('结束回合').click();assert.equal(await page.locator('#dead').isVisible(),true);assert.equal(await page.locator('#review').isVisible(),false);assert.equal(await b('请求撤离').isVisible(),false);assert.deepEqual(errors,[]);
  console.log('PASS browser: cancel, confirmed costs, persistent values, explicit scope/judgment, neutral revision, legal travel, spent opportunity, Boss/hidden/death, safe text and responsive themes.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
