// Limited fictional loop; no native combat, exit hooks, save or philosophical truth claims.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../docs/design/socrates_retreat.html'),'utf8');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
const code=html.match(/\/\/ BEGIN SOCRATES RETREAT PAPER MODEL([\s\S]*?)\/\/ END SOCRATES RETREAT PAPER MODEL/)[1],context={};vm.runInNewContext(code+'\nglobalThis.paper=SocratesRetreatPaper;',context);const p=context.paper;
let total=0;const check=(name,run)=>{run();total++;console.log('PASS '+name);};const snapshot=s=>JSON.stringify(s);
function unchanged(s,fn){const before=snapshot(s);assert.equal(fn(),false);assert.equal(snapshot(s),before);}
function begun(fixture='winnable',definition='necessary'){const s=p.create(fixture);assert.equal(p.begin(s,definition),true);return s;}
function retreat(s,purpose=null){assert.equal(p.request(s),true);const id=s.request.id;assert.equal(p.confirm(s,id,purpose),true);return id;}
function win(s){let n=0;while(s.phase==='combat'){p.play(s,'attack');if(s.phase==='combat'){p.play(s,'defend');p.endTurn(s);}assert.ok(++n<10);}assert.equal(s.phase,'review');}
check('Explicit or unstated definitions precede action without inventing a belief',()=>{for(const d of ['necessary','purpose','unstated']){const s=begun('winnable',d);assert.equal(s.definition,d);assert.equal(s.judgment,null);assert.equal(s.actionPurpose,null);assert.equal(s.spent.length,0);}const s=p.create();unchanged(s,()=>p.begin(s,'bad'));unchanged(s,()=>p.request(s));});
check('Cancel preserves battle and resource state; a later request has a new token',()=>{const s=begun();p.play(s,'attack');p.request(s);const old=s.request.id;const resources=[s.hp,s.gold,s.energy,s.enemyHp,s.block].join(',');assert.equal(p.cancel(s,old),true);assert.equal([s.hp,s.gold,s.energy,s.enemyHp,s.block].join(','),resources);assert.equal(s.spent.length,0);assert.equal(s.actionPurpose,null);p.request(s);assert.notEqual(s.request.id,old);unchanged(s,()=>p.confirm(s,old));});
check('Confirm loses all victory reward, preserves paid losses and prior persistent gold',()=>{const s=begun('persistent');p.play(s,'attack');p.play(s,'defend');p.endTurn(s);assert.equal(s.hp,12);const id=retreat(s,'先保旅程');assert.equal(s.hp,12);assert.equal(s.gold,7);assert.equal(s.rewardStatus,'lost');assert.equal(s.victories,0);assert.equal(s.spent.join(','),'1');assert.equal(s.processed.join(','),'n1');assert.equal(s.actionPurpose,'先保旅程');unchanged(s,()=>p.confirm(s,id));unchanged(s,()=>p.cancel(s,id));});
check('Invalid, dead and stale confirmations leave resources and claims unchanged',()=>{for(const mutate of [s=>s.hp=0,s=>s.epoch++,s=>s.node='n2',s=>s.kind='boss',s=>s.spent.push(1)]){const s=begun();p.request(s);const id=s.request.id;mutate(s);unchanged(s,()=>p.confirm(s,id));}const s=begun();p.request(s);unchanged(s,()=>p.confirm(s,s.request.id,''));unchanged(s,()=>p.confirm(s,s.request.id,'x'.repeat(301)));});
check('Boss never retreats; explicit ordinary request blocks further player actions until resolved',()=>{const b=begun('boss');assert.equal(p.available(b),false);unchanged(b,()=>p.request(b));const s=begun();p.request(s);unchanged(s,()=>p.play(s,'attack'));unchanged(s,()=>p.endTurn(s));unchanged(s,()=>p.request(s));});
check('Normal victory earns reward, retains retreat opportunity and does not certify courage',()=>{const s=begun();win(s);assert.equal(s.hp,19);assert.equal(s.gold,10);assert.equal(s.victories,1);assert.equal(s.spent.length,0);assert.equal(s.judgment,null);assert.equal(s.definition,'necessary');assert.equal(p.tension(s),false);p.judge(s,'courageous');p.setScope(s,true);assert.equal(p.tension(s),false);});
check('Unknown intent stays unknown before action; retreat does not create a risk prediction',()=>{const s=begun('hidden');retreat(s);assert.equal(s.hp,16);assert.equal(s.judgment,null);assert.equal('predictedDamage' in s,false);assert.equal(s.history.some(x=>x.includes('必死')),false);});
check('Keeping standard but prioritising another purpose is not an automatic contradiction',()=>{const s=begun('danger');retreat(s,'这次保旅程');p.judge(s,'standardElse');p.setScope(s,true);assert.equal(p.tension(s),false);assert.equal(s.definition,'necessary');assert.equal(s.judgment,'standardElse');});
check('Only explicit local courage plus explicit scope raises a same-range question',()=>{for(const definition of ['necessary','purpose','unstated']){const s=begun('danger',definition);retreat(s);assert.equal(p.tension(s),false);p.judge(s,'courageous');assert.equal(p.tension(s),false);p.setScope(s,true);assert.equal(p.tension(s),definition==='necessary');assert.equal('virtueScore' in s,false);assert.equal('isCourageous' in s,false);}});
check('Revision targets either statement or leaves question open without changing resources',()=>{for(const a of ['dropNecessary','withdrawJudgment','leaveOpen']){const s=begun('danger');retreat(s);p.judge(s,'courageous');p.setScope(s,true);const r=[s.hp,s.gold,s.spent.join(','),s.victories].join(';');assert.equal(p.adjust(s,a),true);assert.equal([s.hp,s.gold,s.spent.join(','),s.victories].join(';'),r);assert.equal(s.originalDefinition,'necessary');assert.equal(p.tension(s),a==='leaveOpen');unchanged(s,()=>p.adjust(s,a));}});
check('Every response or no response can proceed along the same legal edge with equal resources',()=>{for(const definition of ['necessary','purpose','unstated'])for(const judgment of [null,'standardElse','courageous','notJudged','unanswered']){const s=begun('danger',definition);retreat(s);if(judgment!==null)p.judge(s,judgment);assert.equal(p.proceed(s,'n2'),true);assert.equal(s.hp,12);assert.equal(s.gold,0);assert.equal(s.spent.join(','),'1');assert.equal(s.judgment,judgment);}});
check('Processed node cannot repeat; spent opportunity follows next ordinary combat',()=>{const s=begun();const token=retreat(s);unchanged(s,()=>p.proceed(s,'n1'));unchanged(s,()=>p.proceed(s,'unknown'));p.proceed(s,'n2');p.enter(s);assert.equal(p.available(s),false);assert.equal(s.hp,20);assert.equal(s.gold,0);unchanged(s,()=>p.request(s));unchanged(s,()=>p.confirm(s,token));});
check('Last ordinary combat legally leads to Boss without a refreshed escape',()=>{const s=begun('last');retreat(s);assert.equal(p.destinations(s).join(','),'n4');p.proceed(s,'n4');p.enter(s);assert.equal(s.kind,'boss');assert.equal(p.available(s),false);unchanged(s,()=>p.request(s));});
check('Death does not give victory, retroactive review, escape, reward or resurrection',()=>{const s=begun('danger');p.play(s,'defend');p.endTurn(s);assert.equal(s.phase,'dead');assert.equal(s.hp,0);assert.equal(s.gold,0);assert.equal(s.victories,0);assert.equal(s.spent.length,0);for(const fn of [()=>p.request(s),()=>p.judge(s,'courageous'),()=>p.proceed(s,'n2'),()=>p.enter(s)])unchanged(s,fn);});
check('Continued action purpose is explicit and survives victory; no retroactive death or confirm edits',()=>{const s=begun();unchanged(s,()=>p.recordPurpose(s,''));assert.equal(p.recordPurpose(s,'从现在起争取奖励'),true);win(s);assert.equal(s.actionPurpose,'从现在起争取奖励');unchanged(s,()=>p.recordPurpose(s,'改旧理由'));const r=begun();p.recordPurpose(r,'争取奖励');p.request(r);unchanged(r,()=>p.recordPurpose(r,'请求中改'));p.confirm(r,r.request.id,null);assert.equal(r.actionPurpose,null);assert.ok(r.history.some(x=>x.includes('争取奖励')));});
check('Rest path can continue legally without recovery or reentering old nodes',()=>{const s=begun();retreat(s);p.proceed(s,'n3');assert.equal(s.hp,20);assert.equal(s.gold,0);assert.equal(p.destinations(s).join(','),'n4');unchanged(s,()=>p.enter(s));unchanged(s,()=>p.proceed(s,'n2'));assert.equal(p.proceed(s,'n4'),true);assert.ok(s.processed.includes('n3'));assert.equal(p.enter(s),true);assert.equal(s.kind,'boss');});
check('Next encounter snapshots the revised standard without rewriting the previous testimony',()=>{const s=begun();retreat(s);p.judge(s,'courageous');p.setScope(s,true);p.adjust(s,'dropNecessary');p.proceed(s,'n2');assert.equal(s.encounters[0].originalDefinition,'necessary');assert.equal(s.encounters[0].definition,'actionNotRequired');assert.equal(s.encounters[0].judgment,'courageous');p.enter(s);assert.equal(s.originalDefinition,'actionNotRequired');assert.equal(s.judgment,null);assert.equal(s.encounters[0].originalDefinition,'necessary');});
console.log(`PASS ${total} authored retreat checks; native exit/save and philosophical experience not exercised.`);
